for_breakfast = ["яичница", "горячие бутеры", "сендвичи из Идеи", "что-нибудь из пекары"]
for_lunch = ["Веганы", "Пельмени", "Healthy Bite", "Sweet and green"]
for_dinner = ["Пельмени", "Healthy Bite", "Sweet and green"]
for_flex = ["Tramontana", "Veliki", "Ferdinand Knedli", "Burger House", "Toster"]
for_cooking = ["красную пасту", "белую пасту", "рис с курицей", "говядину с гречкой"]
